import { Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Nightclub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`grid grid-cols-(--full-cols)  ${ubuntu.variable}  antialiased `}>{children}</body>
    </html>
  );
}
